/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsNewRouteImport } from './routes/shows.new'

const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsNewRoute = ShowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShowsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/new': typeof ShowsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/new': typeof ShowsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/new': typeof ShowsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/register'
    | '/shows'
    | '/shows/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/register'
    | '/shows'
    | '/shows/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/login'
    | '/register'
    | '/shows'
    | '/shows/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationRoute: typeof EvaluationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ShowsRoute: typeof ShowsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/new': {
      id: '/shows/new'
      path: '/new'
      fullPath: '/shows/new'
      preLoaderRoute: typeof ShowsNewRouteImport
      parentRoute: typeof ShowsRoute
    }
  }
}

interface ShowsRouteChildren {
  ShowsNewRoute: typeof ShowsNewRoute
}

const ShowsRouteChildren: ShowsRouteChildren = {
  ShowsNewRoute: ShowsNewRoute,
}

const ShowsRouteWithChildren = ShowsRoute._addFileChildren(ShowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvaluationRoute: EvaluationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ShowsRoute: ShowsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
